# Generated by Django 4.2.4 on 2023-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=10)),
                ('data_entrada', models.CharField(max_length=10)),
                ('tipo_fornecedor', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laticinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Legume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=10)),
                ('data_entrada', models.CharField(max_length=10)),
                ('tipo_fornecedor', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verdura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=10)),
                ('data_entrada', models.CharField(max_length=10)),
                ('tipo_fornecedor', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
